// const BASE_URL = "https://api.mtnhao.com/";
export const BASE_URL = "http://localhost:3000/";

// 一些默认数据
// discovery
const bannerList = [
  {
      "imageUrl": "http://p1.music.126.net/S22Khy7j8-psRjxDD5Zmmg==/109951166172407313.jpg",
      "scm": "1.music-homepage.homepage_banner_force.banner.2991979.1659877592.null"
  },
  {
      "imageUrl": "http://p1.music.126.net/ycSr_rJ6ts1a5HRuJKnp5A==/109951166172445357.jpg",
      "scm": "1.music-homepage.homepage_banner_force.banner.2996971.1659826684.null"
  },
  {
      "imageUrl": "http://p1.music.126.net/9zjPTvC3vTiqCd4kZcs0NA==/109951166172428914.jpg",
      "scm": "1.music-homepage.homepage_banner_force.banner.3005986.1659734460.null"
  },
  {
      "imageUrl": "http://p1.music.126.net/efx5WPm0Q8wKW61mSXNuhg==/109951166172209616.jpg",
      "scm": "1.music-homepage.homepage_banner_force.banner.3003974.1659974682.null"
  },
  {
      "imageUrl": "http://p1.music.126.net/KYCQwRSxtLaykIXxGzYzUg==/109951166172268656.jpg",
      "scm": "1.music-homepage.homepage_banner_force.banner.2998984.1659729662.null"
  },
  {
      "imageUrl": "http://p1.music.126.net/ZdvXwu-NErOc11fMZIRQtw==/109951166172143007.jpg",
      "scm": "1.music-homepage.homepage_banner_force.banner.2994977.1659849626.null"
  },
  {
      "imageUrl": "http://p1.music.126.net/S3NNgzIhE6jnt2oN0qwQQw==/109951166172033514.jpg",
      "scm": "1.music-homepage.homepage_banner_force.banner.2981001.1659730500.null"
  }
]
const newPlayLists = [
  {
      "id": 437326740,
      "name": "我只是炸曲的搬运工！【精】",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/aKW94yMBrwaYNYiVHUIP9g==/109951163809833712.jpg",
  },
  {
      "id": 5212378620,
      "name": "“我会从你的世界慢慢消失.”",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/qb2gBjmC9-PYt-n5QFAsjw==/109951165781454309.jpg",
  },
  {
      "id": 2829733864,
      "name": "[睡眠伴侣]  选首最合适你的 然后单曲循环 ",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/CmbQ14DMvVKmUTR4UejdAw==/109951166035763769.jpg",
  },
  {
      "id": 3231649721,
      "name": "百万评论热歌全集丨时实更新中",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/_gMDRNW8RoCvJWHi_p51aA==/109951164726735349.jpg",
  },
  {
      "id": 5382682753,
      "name": "你会对我第二次心动吗",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/GjpC4y21lxvh-wbvRZCPDQ==/109951165602360304.jpg",
  },
  {
      "id": 6728658542,
      "name": "我字字皆你，你却句句非我",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/11718fHt9zby9g4k93WY9w==/109951165922155641.jpg",
  },
  {
      "id": 5252086549,
      "name": "你觉得你和我有遗憾吗？",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/juM9DZlqZP-L_9oGBrkIuQ==/109951165341030471.jpg",
  },
  {
      "id": 3195558821,
      "name": "食我的枪吧（玩马超必备歌单）",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/qu52mTKiCdy1YSWkJ4W-JA==/109951165125531908.jpg",
  },
  {
      "id": 5129450678,
      "name": "你那满目温柔再不属于我（Cover）",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/C1HgiKpjgYt7RrxsAptWvw==/109951166111744559.jpg",
  },
  {
      "id": 4865548839,
      "name": "Chillhop丨深夜独享的静谧时光",
      "copywriter": "热门推荐",
      "picUrl": "https://p2.music.126.net/Vji3PQJAZ2C7gS_6X51NFQ==/109951164723650033.jpg",
  }
]
const newSongsList = [
  {
      "id": 1859925367,
      "type": 4,
      "name": "纵横四海",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/48PncRwL4_BEmpRd_ZohAg==/109951166162802327.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "纵横四海",
          "id": 1859925367,
          "position": 0,
          "alias": [],
          "status": 0,
          "fee": 8,
          "copyrightId": 1416891,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "李荣浩",
                  "id": 4292,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "纵横四海",
              "id": 130148423,
              "type": "Single",
              "size": 1,
              "picId": 109951166162802320,
              "blurPicUrl": "http://p4.music.126.net/48PncRwL4_BEmpRd_ZohAg==/109951166162802327.jpg",
              "companyId": 0,
              "pic": 109951166162802320,
              "picUrl": "http://p3.music.126.net/48PncRwL4_BEmpRd_ZohAg==/109951166162802327.jpg",
              "publishTime": 1625932800000,
              "description": "",
              "tags": "",
              "company": "一样音乐",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [],
              "status": 0,
              "copyrightId": 1416891,
              "commentThreadId": "R_AL_3_130148423",
              "artists": [
                  {
                      "name": "李荣浩",
                      "id": 4292,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166162802327"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 241693,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1859925367",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 0,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 0,
          "hMusic": {
              "name": null,
              "id": 6744911280,
              "size": 9670125,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 241693,
              "volumeDelta": -62214
          },
          "mMusic": {
              "name": null,
              "id": 6744911282,
              "size": 5802093,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 241693,
              "volumeDelta": -59644
          },
          "lMusic": {
              "name": null,
              "id": 6744911284,
              "size": 3868077,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 241693,
              "volumeDelta": -58094
          },
          "bMusic": {
              "name": null,
              "id": 6744911284,
              "size": 3868077,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 241693,
              "volumeDelta": -58094
          },
          "mp3Url": null,
          "exclusive": true,
          "privilege": {
              "id": 1859925367,
              "fee": 8,
              "payed": 0,
              "st": 0,
              "pl": 128000,
              "dl": 0,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 999000,
              "fl": 128000,
              "toast": false,
              "flag": 68,
              "preSell": false,
              "playMaxbr": 999000,
              "downloadMaxbr": 999000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1859657613,
      "type": 4,
      "name": "出走",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/1E3vDff3EGLGllzMr_oJQA==/109951166159431692.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "出走",
          "id": 1859657613,
          "position": 0,
          "alias": [],
          "status": 0,
          "fee": 8,
          "copyrightId": 7003,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "蔡健雅",
                  "id": 7214,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "出走",
              "id": 130099479,
              "type": "Single",
              "size": 1,
              "picId": 109951166159431700,
              "blurPicUrl": "http://p3.music.126.net/1E3vDff3EGLGllzMr_oJQA==/109951166159431692.jpg",
              "companyId": 0,
              "pic": 109951166159431700,
              "picUrl": "http://p4.music.126.net/1E3vDff3EGLGllzMr_oJQA==/109951166159431692.jpg",
              "publishTime": 1625673600000,
              "description": "",
              "tags": "",
              "company": "Go East Music Entertainment Consulting Limited",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [],
              "status": 1,
              "copyrightId": 7003,
              "commentThreadId": "R_AL_3_130099479",
              "artists": [
                  {
                      "name": "蔡健雅",
                      "id": 7214,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166159431692"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 256626,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1859657613",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 1,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 0,
          "hMusic": {
              "name": null,
              "id": 6743212838,
              "size": 10266166,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 256626,
              "volumeDelta": -22344
          },
          "mMusic": {
              "name": null,
              "id": 6743212840,
              "size": 6159717,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 256626,
              "volumeDelta": -19707
          },
          "lMusic": {
              "name": null,
              "id": 6743212842,
              "size": 4106493,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 256626,
              "volumeDelta": -17914
          },
          "bMusic": {
              "name": null,
              "id": 6743212842,
              "size": 4106493,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 256626,
              "volumeDelta": -17914
          },
          "mp3Url": null,
          "exclusive": false,
          "privilege": {
              "id": 1859657613,
              "fee": 8,
              "payed": 0,
              "st": 0,
              "pl": 128000,
              "dl": 0,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 320000,
              "fl": 128000,
              "toast": false,
              "flag": 4,
              "preSell": false,
              "playMaxbr": 320000,
              "downloadMaxbr": 320000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1859979159,
      "type": 4,
      "name": "快乐感",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/Lwmnl43bus-meCFswauTrw==/109951166163389352.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "快乐感",
          "id": 1859979159,
          "position": 0,
          "alias": [
              "2021《快乐大本营》全新主题曲/片头曲"
          ],
          "status": 0,
          "fee": 0,
          "copyrightId": 2706485,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "时代少年团",
                  "id": 33806754,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "快乐感",
              "id": 130155344,
              "type": "Single",
              "size": 1,
              "picId": 109951166163389340,
              "blurPicUrl": "http://p3.music.126.net/Lwmnl43bus-meCFswauTrw==/109951166163389352.jpg",
              "companyId": 0,
              "pic": 109951166163389340,
              "picUrl": "http://p4.music.126.net/Lwmnl43bus-meCFswauTrw==/109951166163389352.jpg",
              "publishTime": 1625932800000,
              "description": "",
              "tags": "",
              "company": "湖南广播影视集团有限公司卫视频道分公司",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [
                  "2021《快乐大本营》全新主题曲/片头曲"
              ],
              "status": 0,
              "copyrightId": 2706485,
              "commentThreadId": "R_AL_3_130155344",
              "artists": [
                  {
                      "name": "时代少年团",
                      "id": 33806754,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166163389352"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 216320,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1859979159",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 0,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 0,
          "hMusic": {
              "name": null,
              "id": 6745134380,
              "size": 8654933,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 216320,
              "volumeDelta": -67811
          },
          "mMusic": {
              "name": null,
              "id": 6745134382,
              "size": 5192977,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 216320,
              "volumeDelta": -65326
          },
          "lMusic": {
              "name": null,
              "id": 6745134384,
              "size": 3461999,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 216320,
              "volumeDelta": -63890
          },
          "bMusic": {
              "name": null,
              "id": 6745134384,
              "size": 3461999,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 216320,
              "volumeDelta": -63890
          },
          "mp3Url": null,
          "exclusive": false,
          "privilege": {
              "id": 1859979159,
              "fee": 0,
              "payed": 0,
              "st": 0,
              "pl": 320000,
              "dl": 999000,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 999000,
              "fl": 320000,
              "toast": false,
              "flag": 1,
              "preSell": false,
              "playMaxbr": 999000,
              "downloadMaxbr": 999000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1860129265,
      "type": 4,
      "name": "温情",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/GjcS7hZCMTM-8W8YJDGgkw==/109951166165214251.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "温情",
          "id": 1860129265,
          "position": 0,
          "alias": [],
          "status": 0,
          "fee": 0,
          "copyrightId": 0,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "刘森",
                  "id": 32673826,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "华北浪革",
              "id": 130185746,
              "type": "专辑",
              "size": 1,
              "picId": 109951166165214260,
              "blurPicUrl": "http://p3.music.126.net/GjcS7hZCMTM-8W8YJDGgkw==/109951166165214251.jpg",
              "companyId": 0,
              "pic": 109951166165214260,
              "picUrl": "http://p3.music.126.net/GjcS7hZCMTM-8W8YJDGgkw==/109951166165214251.jpg",
              "publishTime": 1625932800000,
              "description": "",
              "tags": "",
              "company": "华北浪革",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [],
              "status": 0,
              "copyrightId": -1,
              "commentThreadId": "R_AL_3_130185746",
              "artists": [
                  {
                      "name": "刘森",
                      "id": 32673826,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166165214251"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 188101,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1860129265",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 0,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 0,
          "hMusic": {
              "name": null,
              "id": 6746027017,
              "size": 7526444,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 320002,
              "playTime": 188101,
              "volumeDelta": -81001
          },
          "mMusic": {
              "name": null,
              "id": 6746027019,
              "size": 4515884,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 192002,
              "playTime": 188101,
              "volumeDelta": -78372
          },
          "lMusic": {
              "name": null,
              "id": 6746027021,
              "size": 3010604,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128002,
              "playTime": 188101,
              "volumeDelta": -76631
          },
          "bMusic": {
              "name": null,
              "id": 6746027021,
              "size": 3010604,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128002,
              "playTime": 188101,
              "volumeDelta": -76631
          },
          "mp3Url": null,
          "exclusive": false,
          "privilege": {
              "id": 1860129265,
              "fee": 0,
              "payed": 0,
              "st": 0,
              "pl": 320000,
              "dl": 999000,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 999000,
              "fl": 320000,
              "toast": false,
              "flag": 129,
              "preSell": false,
              "playMaxbr": 999000,
              "downloadMaxbr": 999000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1859729200,
      "type": 4,
      "name": "不归渡",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/3QazhTRsPIjPoFUwwp6B_g==/109951166160259577.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "不归渡",
          "id": 1859729200,
          "position": 0,
          "alias": [
              "《轩辕剑龙舞云山》云渡昆仑资料片主题曲"
          ],
          "status": 0,
          "fee": 0,
          "copyrightId": 2708477,
          "disc": "01",
          "no": 0,
          "artists": [
              {
                  "name": "李振宁",
                  "id": 32727341,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              {
                  "name": "轩辕剑龙舞云山",
                  "id": 46655973,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "不归渡",
              "id": 130108763,
              "type": "EP",
              "size": 2,
              "picId": 109951166160259580,
              "blurPicUrl": "http://p4.music.126.net/3QazhTRsPIjPoFUwwp6B_g==/109951166160259577.jpg",
              "companyId": 0,
              "pic": 109951166160259580,
              "picUrl": "http://p4.music.126.net/3QazhTRsPIjPoFUwwp6B_g==/109951166160259577.jpg",
              "publishTime": 1625760000000,
              "description": "",
              "tags": "",
              "company": "网易",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [],
              "status": 0,
              "copyrightId": 2708477,
              "commentThreadId": "R_AL_3_130108763",
              "artists": [
                  {
                      "name": "李振宁",
                      "id": 32727341,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  },
                  {
                      "name": "轩辕剑龙舞云山",
                      "id": 46655973,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166160259577"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 317651,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1859729200",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 0,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 0,
          "hMusic": {
              "name": null,
              "id": 6743603743,
              "size": 12708525,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 317651,
              "volumeDelta": -43445
          },
          "mMusic": {
              "name": null,
              "id": 6743603745,
              "size": 7625133,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 317651,
              "volumeDelta": -40961
          },
          "lMusic": {
              "name": null,
              "id": 6743603747,
              "size": 5083437,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 317651,
              "volumeDelta": -39420
          },
          "bMusic": {
              "name": null,
              "id": 6743603747,
              "size": 5083437,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 317651,
              "volumeDelta": -39420
          },
          "mp3Url": null,
          "exclusive": true,
          "privilege": {
              "id": 1859729200,
              "fee": 0,
              "payed": 0,
              "st": 0,
              "pl": 320000,
              "dl": 999000,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 999000,
              "fl": 320000,
              "toast": false,
              "flag": 65,
              "preSell": false,
              "playMaxbr": 999000,
              "downloadMaxbr": 999000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1859245776,
      "type": 4,
      "name": "Stay",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/e5cvcdgeosDKTDrkTfZXnQ==/109951166155165682.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "Stay",
          "id": 1859245776,
          "position": 0,
          "alias": [],
          "status": 0,
          "fee": 8,
          "copyrightId": 7001,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "The Kid LAROI",
                  "id": 32795025,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              {
                  "name": "Justin Bieber",
                  "id": 35531,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "Stay",
              "id": 130016223,
              "type": "Single",
              "size": 1,
              "picId": 109951166155165680,
              "blurPicUrl": "http://p4.music.126.net/e5cvcdgeosDKTDrkTfZXnQ==/109951166155165682.jpg",
              "companyId": 0,
              "pic": 109951166155165680,
              "picUrl": "http://p3.music.126.net/e5cvcdgeosDKTDrkTfZXnQ==/109951166155165682.jpg",
              "publishTime": 1625760000000,
              "description": "",
              "tags": "",
              "company": "索尼音乐",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [],
              "status": 1,
              "copyrightId": 7001,
              "commentThreadId": "R_AL_3_130016223",
              "artists": [
                  {
                      "name": "The Kid LAROI",
                      "id": 32795025,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  },
                  {
                      "name": "Justin Bieber",
                      "id": 35531,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166155165682"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 141871,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1859245776",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 1,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 14298179,
          "hMusic": {
              "name": null,
              "id": 6740607313,
              "size": 5674885,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 141871,
              "volumeDelta": -65994
          },
          "mMusic": {
              "name": null,
              "id": 6740607315,
              "size": 3404948,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 141871,
              "volumeDelta": -63413
          },
          "lMusic": {
              "name": null,
              "id": 6740607317,
              "size": 2269980,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 141871,
              "volumeDelta": -61765
          },
          "bMusic": {
              "name": null,
              "id": 6740607317,
              "size": 2269980,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 141871,
              "volumeDelta": -61765
          },
          "mp3Url": null,
          "exclusive": false,
          "privilege": {
              "id": 1859245776,
              "fee": 8,
              "payed": 0,
              "st": 0,
              "pl": 128000,
              "dl": 0,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 320000,
              "fl": 128000,
              "toast": false,
              "flag": 4,
              "preSell": false,
              "playMaxbr": 320000,
              "downloadMaxbr": 320000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1859652717,
      "type": 4,
      "name": "Moon Halo",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/ciLKATqflV2YWSV3ltE2Kw==/109951166159281275.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "Moon Halo",
          "id": 1859652717,
          "position": 0,
          "alias": [
              "崩坏3《薪炎永燃》动画短片印象曲"
          ],
          "status": 0,
          "fee": 0,
          "copyrightId": 0,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "茶理理",
                  "id": 1003026,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              {
                  "name": "TetraCalyx",
                  "id": 1081556,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              {
                  "name": "Hanser",
                  "id": 1049179,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "Moon Halo",
              "id": 130098008,
              "type": "Single",
              "size": 2,
              "picId": 109951166159281280,
              "blurPicUrl": "http://p4.music.126.net/ciLKATqflV2YWSV3ltE2Kw==/109951166159281275.jpg",
              "companyId": 0,
              "pic": 109951166159281280,
              "picUrl": "http://p4.music.126.net/ciLKATqflV2YWSV3ltE2Kw==/109951166159281275.jpg",
              "publishTime": 1625760000000,
              "description": "",
              "tags": "",
              "company": "miHoYo",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [
                  "崩坏3《薪炎永燃》动画短片印象曲"
              ],
              "status": 0,
              "copyrightId": -1,
              "commentThreadId": "R_AL_3_130098008",
              "artists": [
                  {
                      "name": "HOYO-MiX",
                      "id": 12487174,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166159281275"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 204054,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1859652717",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 0,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 14299094,
          "hMusic": {
              "name": null,
              "id": 6743145428,
              "size": 8164845,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 320002,
              "playTime": 204054,
              "volumeDelta": -57813
          },
          "mMusic": {
              "name": null,
              "id": 6743145430,
              "size": 4898925,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 192002,
              "playTime": 204054,
              "volumeDelta": -55315
          },
          "lMusic": {
              "name": null,
              "id": 6743145432,
              "size": 3265965,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128002,
              "playTime": 204054,
              "volumeDelta": -53917
          },
          "bMusic": {
              "name": null,
              "id": 6743145432,
              "size": 3265965,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128002,
              "playTime": 204054,
              "volumeDelta": -53917
          },
          "mp3Url": null,
          "exclusive": true,
          "privilege": {
              "id": 1859652717,
              "fee": 0,
              "payed": 0,
              "st": 0,
              "pl": 320000,
              "dl": 999000,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 999000,
              "fl": 320000,
              "toast": false,
              "flag": 64,
              "preSell": false,
              "playMaxbr": 999000,
              "downloadMaxbr": 999000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1859100914,
      "type": 4,
      "name": "济公",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/ArwM1mcPViVYbUE_2Co7tQ==/109951166153445155.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "济公",
          "id": 1859100914,
          "position": 0,
          "alias": [
              "电影《济公之降龙降世》主题曲"
          ],
          "status": 0,
          "fee": 0,
          "copyrightId": 0,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "戴荃",
                  "id": 791534,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "济公",
              "id": 129994480,
              "type": "Single",
              "size": 2,
              "picId": 109951166153445150,
              "blurPicUrl": "http://p3.music.126.net/ArwM1mcPViVYbUE_2Co7tQ==/109951166153445155.jpg",
              "companyId": 0,
              "pic": 109951166153445150,
              "picUrl": "http://p3.music.126.net/ArwM1mcPViVYbUE_2Co7tQ==/109951166153445155.jpg",
              "publishTime": 1625673600000,
              "description": "",
              "tags": "",
              "company": "北京立马影视传媒有限公司",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [
                  "电影《济公之降龙降世》主题曲"
              ],
              "status": 0,
              "copyrightId": -1,
              "commentThreadId": "R_AL_3_129994480",
              "artists": [
                  {
                      "name": "戴荃",
                      "id": 791534,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166153445155"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 198529,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1859100914",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 0,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 14298739,
          "hMusic": {
              "name": null,
              "id": 6742901260,
              "size": 7944045,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 198529,
              "volumeDelta": -41261
          },
          "mMusic": {
              "name": null,
              "id": 6742901262,
              "size": 4766445,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 198529,
              "volumeDelta": -38749
          },
          "lMusic": {
              "name": null,
              "id": 6742901264,
              "size": 3177645,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 198529,
              "volumeDelta": -37315
          },
          "bMusic": {
              "name": null,
              "id": 6742901264,
              "size": 3177645,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 198529,
              "volumeDelta": -37315
          },
          "mp3Url": null,
          "exclusive": false,
          "privilege": {
              "id": 1859100914,
              "fee": 0,
              "payed": 0,
              "st": 0,
              "pl": 320000,
              "dl": 999000,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 999000,
              "fl": 320000,
              "toast": false,
              "flag": 0,
              "preSell": false,
              "playMaxbr": 999000,
              "downloadMaxbr": 999000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1853922204,
      "type": 4,
      "name": "グレースノート（灰度笔记本）",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/BW6319Kp3WbeccL0fOd5kQ==/109951166093775756.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "グレースノート（灰度笔记本）",
          "id": 1853922204,
          "position": 0,
          "alias": [
              "短篇动画《夜之国》第二夜主题曲"
          ],
          "status": 0,
          "fee": 8,
          "copyrightId": 7001,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "Aimer",
                  "id": 16152,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "グレースノート",
              "id": 129135042,
              "type": "Single",
              "size": 1,
              "picId": 109951166093775760,
              "blurPicUrl": "http://p4.music.126.net/BW6319Kp3WbeccL0fOd5kQ==/109951166093775756.jpg",
              "companyId": 0,
              "pic": 109951166093775760,
              "picUrl": "http://p4.music.126.net/BW6319Kp3WbeccL0fOd5kQ==/109951166093775756.jpg",
              "publishTime": 1625328000000,
              "description": "",
              "tags": "",
              "company": "索尼音乐",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [],
              "status": 1,
              "copyrightId": 7001,
              "commentThreadId": "R_AL_3_129135042",
              "artists": [
                  {
                      "name": "Aimer",
                      "id": 16152,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166093775756"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 299911,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1853922204",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 1,
          "transName": "grace note",
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 14298622,
          "hMusic": {
              "name": null,
              "id": 6710451148,
              "size": 11997562,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 299911,
              "volumeDelta": -65954
          },
          "mMusic": {
              "name": null,
              "id": 6710451150,
              "size": 7198555,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 299911,
              "volumeDelta": -63457
          },
          "lMusic": {
              "name": null,
              "id": 6710451152,
              "size": 4799051,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 299911,
              "volumeDelta": -61872
          },
          "bMusic": {
              "name": null,
              "id": 6710451152,
              "size": 4799051,
              "extension": "mp3",
              "sr": 44100,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 299911,
              "volumeDelta": -61872
          },
          "mp3Url": null,
          "transNames": [
              "grace note"
          ],
          "exclusive": false,
          "privilege": {
              "id": 1853922204,
              "fee": 8,
              "payed": 0,
              "st": 0,
              "pl": 128000,
              "dl": 0,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 320000,
              "fl": 128000,
              "toast": false,
              "flag": 4,
              "preSell": false,
              "playMaxbr": 320000,
              "downloadMaxbr": 320000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  },
  {
      "id": 1858811967,
      "type": 4,
      "name": "삠삠 (BEAM BEAM)",
      "copywriter": null,
      "picUrl": "http://p1.music.126.net/b7kIdFmREERIINwc_5Gu9Q==/109951166150205963.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "song": {
          "name": "삠삠 (BEAM BEAM)",
          "id": 1858811967,
          "position": 0,
          "alias": [],
          "status": 0,
          "fee": 8,
          "copyrightId": 1415873,
          "disc": "01",
          "no": 1,
          "artists": [
              {
                  "name": "田小娟",
                  "id": 12073588,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              }
          ],
          "album": {
              "name": "Windy",
              "id": 129952587,
              "type": "EP",
              "size": 5,
              "picId": 109951166150205970,
              "blurPicUrl": "http://p3.music.126.net/b7kIdFmREERIINwc_5Gu9Q==/109951166150205963.jpg",
              "companyId": 0,
              "pic": 109951166150205970,
              "picUrl": "http://p3.music.126.net/b7kIdFmREERIINwc_5Gu9Q==/109951166150205963.jpg",
              "publishTime": 1625414400000,
              "description": "",
              "tags": "",
              "company": "Cube Entertainment",
              "briefDesc": "",
              "artist": {
                  "name": "",
                  "id": 0,
                  "picId": 0,
                  "img1v1Id": 0,
                  "briefDesc": "",
                  "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                  "albumSize": 0,
                  "alias": [],
                  "trans": "",
                  "musicSize": 0,
                  "topicPerson": 0
              },
              "songs": [],
              "alias": [],
              "status": 0,
              "copyrightId": 1415873,
              "commentThreadId": "R_AL_3_129952587",
              "artists": [
                  {
                      "name": "田小娟",
                      "id": 12073588,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0,
                      "topicPerson": 0
                  }
              ],
              "subType": "录音室版",
              "transName": null,
              "onSale": false,
              "mark": 0,
              "picId_str": "109951166150205963"
          },
          "starred": false,
          "popularity": 100,
          "score": 100,
          "starredNum": 0,
          "duration": 167853,
          "playedNum": 0,
          "dayPlays": 0,
          "hearTime": 0,
          "ringtone": "",
          "crbt": null,
          "audition": null,
          "copyFrom": "",
          "commentThreadId": "R_SO_4_1858811967",
          "rtUrl": null,
          "ftype": 0,
          "rtUrls": [],
          "copyright": 0,
          "transName": null,
          "sign": null,
          "mark": 0,
          "originCoverType": 0,
          "originSongSimpleData": null,
          "single": 0,
          "noCopyrightRcmd": null,
          "rtype": 0,
          "rurl": null,
          "mvid": 14298646,
          "hMusic": {
              "name": null,
              "id": 6738586551,
              "size": 6716205,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 320000,
              "playTime": 167853,
              "volumeDelta": -74995
          },
          "mMusic": {
              "name": null,
              "id": 6738586553,
              "size": 4029741,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 192000,
              "playTime": 167853,
              "volumeDelta": -72515
          },
          "lMusic": {
              "name": null,
              "id": 6738586555,
              "size": 2686509,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 167853,
              "volumeDelta": -71170
          },
          "bMusic": {
              "name": null,
              "id": 6738586555,
              "size": 2686509,
              "extension": "mp3",
              "sr": 48000,
              "dfsId": 0,
              "bitrate": 128000,
              "playTime": 167853,
              "volumeDelta": -71170
          },
          "mp3Url": null,
          "exclusive": true,
          "privilege": {
              "id": 1858811967,
              "fee": 8,
              "payed": 0,
              "st": 0,
              "pl": 128000,
              "dl": 0,
              "sp": 7,
              "cp": 1,
              "subp": 1,
              "cs": false,
              "maxbr": 999000,
              "fl": 128000,
              "toast": false,
              "flag": 68,
              "preSell": false,
              "playMaxbr": 999000,
              "downloadMaxbr": 999000,
              "rscl": null,
              "freeTrialPrivilege": {
                  "resConsumable": false,
                  "userConsumable": false
              },
              "chargeInfoList": [
                  {
                      "rate": 128000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 0
                  },
                  {
                      "rate": 192000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 320000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  },
                  {
                      "rate": 999000,
                      "chargeUrl": null,
                      "chargeMessage": null,
                      "chargeType": 1
                  }
              ]
          }
      },
      "alg": "hot_server"
  }
]
const newMvsList = [
  {
      "id": 14298969,
      "type": 5,
      "name": "世界の中心で虹を叫んだサマー",
      "copywriter": "最新热门MV推荐",
      "picUrl": "https://p1.music.126.net/345oST5ogDjAEfCJ-q6J2w==/109951166159463296.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "duration": 341000,
      "playCount": 4881,
      "subed": false,
      "artists": [
          {
              "id": 1135142,
              "name": "虹のコンキスタドール"
          }
      ],
      "artistName": "虹のコンキスタドール",
      "artistId": 1135142,
      "alg": "hot_server"
  },
  {
      "id": 14299485,
      "type": 5,
      "name": "Apple Blossom Time (Live On The Ed Sullivan Show, May 30, 1965)",
      "copywriter": "最新热门MV推荐",
      "picUrl": "https://p1.music.126.net/WwXqP1idpwFxQ710CEV6Zg==/109951166176151123.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "duration": 110000,
      "playCount": 345,
      "subed": false,
      "artists": [
          {
              "id": 84417,
              "name": "Wayne Newton"
          }
      ],
      "artistName": "Wayne Newton",
      "artistId": 84417,
      "alg": "hot_server"
  },
  {
      "id": 14299446,
      "type": 5,
      "name": "Don't Jealous Me - Renan Choreography",
      "copywriter": "最新热门MV推荐",
      "picUrl": "https://p1.music.126.net/Fy7_f19CLGfhCKBCQFH65A==/109951166174905445.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "duration": 219000,
      "playCount": 490,
      "subed": false,
      "artists": [
          {
              "id": 12155385,
              "name": "1 MILLION"
          }
      ],
      "artistName": "1 MILLION",
      "artistId": 12155385,
      "alg": "hot_server"
  },
  {
      "id": 14299442,
      "type": 5,
      "name": "SOLO Remix - Learner's Class",
      "copywriter": "最新热门MV推荐",
      "picUrl": "https://p1.music.126.net/NX6f3WhGzTiko9T1HnBFOw==/109951166174911595.jpg",
      "canDislike": true,
      "trackNumberUpdateTime": null,
      "duration": 122000,
      "playCount": 531,
      "subed": false,
      "artists": [
          {
              "id": 12155385,
              "name": "1 MILLION"
          }
      ],
      "artistName": "1 MILLION",
      "artistId": 12155385,
      "alg": "hot_server"
  }
]
export { bannerList, newSongsList, newPlayLists, newMvsList }